(() => {
  "use strict";

  const chapter = (id, number, title, description, prompts) => ({
    id,
    number,
    title,
    description,
    decisions: prompts.map((prompt, index) => ({
      id: `${id}-${String(index + 1).padStart(2, "0")}`,
      number: `${number}.${String(index + 1).padStart(2, "0")}`,
      prompt,
    })),
  });

  const chapters = [
    chapter(
      "identity",
      "01",
      "Permanent identity",
      "What remains recognizably Froni when each edition is allowed to become a different visual world.",
      [
        "Where should recognition live when an edition may change color, imagery, layout, and atmosphere completely?",
        "What exact job belongs to the wordmark on the website?",
        "What exact job belongs to the F brandmark on the website?",
        "Which elements must remain invariant across every edition?",
        "Which elements must be forbidden from becoming permanent house signatures?",
        "How much visual difference between consecutive editions should the system tolerate?",
        "At what point does edition freedom become loss of house recognition?",
        "Should recognition be strongest on first contact, during use, or in the permanent record?",
        "How should the house be recognized when the current edition image is absent?",
        "How should the system prove continuity after ten radically different editions?",
        "Which identity decisions belong only to digital surfaces?",
        "Which website constants may later extend to certificates, email, or packaging?",
      ],
    ),
    chapter(
      "edition-change",
      "02",
      "Edition change",
      "How a new work takes over the website without making the house look replaced.",
      [
        "How much of the website may change when a new edition enters public view?",
        "What should happen to the previous edition at the moment of transition?",
        "Should the change feel immediate, gradual, or visibly staged?",
        "Which visual decisions are made once per edition?",
        "Which behavioral decisions are made once per edition?",
        "Which content modules may appear only when a work requires them?",
        "How should the system handle an edition whose dominant color is difficult on screen?",
        "How should the system handle an edition with no suitable hero image?",
        "How should the system handle a non-clothing edition?",
        "How should the system handle two privately developing works while only one is public?",
        "How much of an edition’s visual system survives into its permanent record?",
        "What must be tested before an edition-specific treatment is allowed to replace the current one?",
      ],
    ),
    chapter(
      "time",
      "03",
      "Time and state",
      "The relationship between introduction, commerce, allocation, making, delivery, and permanent record.",
      [
        "What remains constant as one edition page moves through time?",
        "How visibly different should the introduction and commerce states be?",
        "What exact event changes introduction into commerce?",
        "What exact event changes commerce into permanent record?",
        "How should the site behave if allocation happens before the public opening?",
        "How should the site describe a temporarily unavailable service without simulating scarcity?",
        "Should making and fulfilment progress become a public state of the edition page?",
        "How should dates be shown before, during, and after commerce?",
        "How should historical states remain legible without exposing obsolete controls?",
        "Should a visitor ever be able to inspect a previous state of the page?",
        "How should the page handle a cancelled, paused, or indefinitely delayed edition?",
        "What must remain at the same URL throughout the life of an edition?",
        "Which state changes require a new visual confirmation before release?",
      ],
    ),
    chapter(
      "architecture",
      "04",
      "Information architecture",
      "The smallest complete structure for the house, the current work, and the growing record.",
      [
        "What is the minimum permanent navigation the website needs?",
        "Should the current work be the home page or a destination reached from it?",
        "Where should completed editions live?",
        "Where should house principles live, if they appear at all?",
        "Where should care and repair information live?",
        "Where should press and institutional information live?",
        "Where should legal information live without feeling appended?",
        "Should search exist before the archive is large enough to require it?",
        "When does filtering become useful rather than bureaucratic?",
        "How should a person move from an edition record to its source material?",
        "How should a person return from deep archive material to the current work?",
        "Which destinations should never enter the primary navigation?",
        "How should translated routes preserve the same architecture?",
        "What should a direct link to a deep record reveal before any other site context?",
      ],
    ),
    chapter(
      "current",
      "05",
      "Current work",
      "How the one public work occupies the primary place without becoming a conventional campaign or shop.",
      [
        "What should a first viewport establish before the visitor scrolls?",
        "How much of the object must be visible immediately?",
        "Should the first contact begin with object, source, title, or date?",
        "How should the work remain dominant without making the page empty?",
        "What amount of context belongs beside the first image?",
        "What should the first deliberate action be?",
        "How should the page distinguish looking from buying?",
        "How should the page behave when the current work is not yet purchasable?",
        "How should the page behave when the current work has been allocated?",
        "What makes the current work feel singular without using urgency?",
        "How much of the archive should be visible from the current-work page?",
        "How should the current work remain clear on a small phone in one glance?",
      ],
    ),
    chapter(
      "edition-page",
      "06",
      "Edition page",
      "The complete account of one work: object, source, making, practical facts, commerce, and record.",
      [
        "What is the governing order of an edition page?",
        "How should title, edition number, dates, and cap relate visually?",
        "How should the source be identified before interpretation begins?",
        "How should object photographs and source images coexist?",
        "Where should material and construction specifications appear?",
        "Where should measurements and fit appear?",
        "How should making evidence deepen without becoming a process dump?",
        "How should the page distinguish permanent facts from temporary commerce controls?",
        "How should price enter without becoming the visual argument?",
        "How should delivery and border-charge facts enter without disrupting the work?",
        "Where should the physical certificate be represented?",
        "What remains after purchase controls disappear?",
        "How should very long scholarship be entered and left?",
        "How should a sparse edition page avoid thinness?",
        "How should a dense edition page avoid clutter?",
      ],
    ),
    chapter(
      "layout",
      "07",
      "Grid and composition",
      "The spatial system that permits strong art direction while keeping orientation and use clear.",
      [
        "How explicit should the governing grid be?",
        "Should the grid remain fixed or adapt by edition?",
        "What should determine the page’s maximum width?",
        "When should content break the grid?",
        "How should full-bleed imagery be earned?",
        "What amount of negative space signals importance rather than absence?",
        "How should frames be used without creating a museum microsite?",
        "How should layering be used without hiding information?",
        "What may live in margins?",
        "How should captions relate to images at different sizes?",
        "Should scrolling be continuous, sectional, or mixed?",
        "How should long pages reveal their structure without persistent clutter?",
        "What alignment behavior should remain constant on mobile?",
        "Which desktop compositions cannot survive and therefore should not be designed?",
      ],
    ),
    chapter(
      "type",
      "08",
      "Typography and language",
      "A multilingual system for display, reading, records, numbers, religious terms, and practical information.",
      [
        "What should the primary serif do?",
        "What should the sans serif do?",
        "How much contrast should exist between display and reading roles?",
        "How should the wordmark relate to surrounding live type?",
        "How should numerals behave in edition records?",
        "How should Greek be supported without appearing imported?",
        "How should Albanian enter if it becomes a secondary house language?",
        "How should complete local translations affect line length and hierarchy?",
        "What type sizes make the site monumental without sacrificing reading?",
        "How should long-form scholarship differ from product information?",
        "How should labels and technical facts differ from body copy?",
        "When are capitals appropriate?",
        "How should links be visible without conventional blue or decorative underlining everywhere?",
        "Which weights survive dark and light edition grounds?",
        "What typographic behavior must remain stable across every edition?",
      ],
    ),
    chapter(
      "color",
      "09",
      "Color and surfaces",
      "How edition-specific color can change radically while contrast, hierarchy, and recognition remain reliable.",
      [
        "Which surfaces may take the edition’s dominant color?",
        "Does the house need any permanent digital neutral?",
        "How should the wordmark adapt to changing grounds?",
        "How should an edition use several strong colors without noise?",
        "How should an entirely black edition avoid inheriting the rejected old site?",
        "How should an entirely pale edition retain gravity?",
        "When may color carry navigation or state information?",
        "How should color changes occur between introduction, commerce, and record?",
        "Which color pairings must be rejected for accessibility?",
        "How should printed color studies inform screen decisions without binding them?",
        "How should the system respond when a historical source has its own authoritative color?",
        "What must never be inferred as a permanent sacred color code?",
      ],
    ),
    chapter(
      "sacred-image",
      "10",
      "Sacred source handling",
      "How sacred and historical material is identified, shown, cropped, magnified, and placed without becoming decoration.",
      [
        "What should be seen first: source image, transformed object, or their relationship?",
        "How should a source’s damage and age remain visible?",
        "When is cropping a sacred image acceptable?",
        "How should any crop be documented?",
        "How should magnification work without turning the source into spectacle?",
        "How should source and derivative remain unmistakably distinct?",
        "How should provenance appear beside an image?",
        "How should museum, monastery, inventory, date, and rights information be ordered?",
        "How should uncertainty in provenance be stated?",
        "What kind of image transition would trivialize the source?",
        "When should a sacred image not appear in a thumbnail?",
        "How should alt text identify the source without interpretation?",
        "How should source-specific restrictions override the general page system?",
        "What review must occur before sacred imagery is published?",
      ],
    ),
    chapter(
      "media",
      "11",
      "Photography and film",
      "The image system for object, material, construction, human presence, source, and longer encounters.",
      [
        "What is the primary photographic world for Edition One?",
        "How formal should studio control feel?",
        "What kind of human presence is meaningful rather than lifestyle staging?",
        "Which object views are required before purchase?",
        "Which construction details require dedicated images?",
        "How should scale be shown?",
        "How should photography distinguish front, back, interior, and worn views?",
        "When should an image be full bleed?",
        "How should image sequences behave on a phone?",
        "What belongs in film that still photography cannot carry?",
        "Should film begin automatically in any context?",
        "How should captions, transcripts, and audio descriptions be handled?",
        "How should thumbnails avoid reducing sacred or detailed imagery to noise?",
        "What compression and resolution floor protects stitch and material detail?",
      ],
    ),
    chapter(
      "interaction",
      "12",
      "Motion and interaction",
      "The behavior of navigation, selection, transitions, disclosure, focus, and feedback.",
      [
        "What is the maximum role of motion in the house identity?",
        "Should the page move on first load?",
        "How should state transitions feel without becoming a campaign reveal?",
        "What interactions deserve animation?",
        "What interactions should remain immediate?",
        "How should hover help without hiding essential information?",
        "How should keyboard focus appear on every edition color system?",
        "How should expandable detail preserve orientation?",
        "How should a gallery move without trapping scroll?",
        "How should loading states remain quiet but unmistakable?",
        "How should errors interrupt without becoming visually dominant?",
        "Should sound exist anywhere on the website?",
        "What survives when reduced motion is requested?",
        "What survives when JavaScript fails?",
      ],
    ),
    chapter(
      "capture",
      "13",
      "Introduction and capture",
      "The state before commerce opens: first contact, the work, the address field, consent, and what follows.",
      [
        "What is the introduction state’s single purpose?",
        "How much of the work should be disclosed before opening?",
        "What must remain withheld until later communication?",
        "Where should the address field appear?",
        "How should the field and button relate to the work visually?",
        "What exact practical promise belongs beside consent?",
        "How should double opt-in be explained?",
        "What should happen immediately after submission?",
        "What should the check-your-inbox state preserve from the page?",
        "How should invalid, duplicate, blocked, and server-error states differ?",
        "How should the form work with JavaScript disabled?",
        "How should the mobile keyboard affect the composition?",
        "Should early access be visible before the address is submitted?",
        "What should a returning subscriber see?",
      ],
    ),
    chapter(
      "commerce",
      "14",
      "Commerce state",
      "A direct made-to-order purchase path with complete evidence and no scarcity theatre.",
      [
        "What changes visually when commerce opens?",
        "Where should purchase controls enter the edition page?",
        "How should price be shown without being justified?",
        "How should local currency be determined and corrected?",
        "How should the literal edition cap be stated?",
        "How should numbering be explained?",
        "How should made-to-order timing be shown?",
        "How should size selection work?",
        "How should measurements and fit remain near size selection?",
        "How should unavailable sizes or configurations be handled?",
        "How should included delivery and border charges be stated?",
        "How should return terms remain available before purchase?",
        "Should a cart exist for a one-work house?",
        "How should purchase confirmation return the person to the work?",
        "How should allocation be communicated without a counter?",
        "What should happen at the exact moment the cap is reached?",
      ],
    ),
    chapter(
      "record",
      "15",
      "Permanent record and archive",
      "How a completed edition remains useful, authoritative, and alive without residual shop behavior.",
      [
        "What changes when an edition becomes a permanent record?",
        "Which commerce elements disappear completely?",
        "Which temporary facts become permanent historical facts?",
        "How should the allocation date be shown?",
        "How should the final cap and numbering record be preserved?",
        "What making evidence should be added after delivery?",
        "What scholarship belongs only after the edition closes?",
        "How should corrections to a permanent record be documented?",
        "What is the governing order of the archive index?",
        "Should archive entries be grouped by year, medium, subject, or sequence?",
        "How should one current work sit beside many completed works?",
        "When should archive search appear?",
        "When should filters appear?",
        "How should a permanent record remain visually related to its original edition world?",
        "How should care, repair, and authentication updates attach to an old edition?",
        "What makes the archive substantial without becoming institutional?",
      ],
    ),
    chapter(
      "service",
      "16",
      "Checkout and service",
      "Plain purchase completion, order progress, human recovery, delivery, returns, care, and repair.",
      [
        "How visually separate should checkout be from the edition page?",
        "What minimum information belongs in checkout?",
        "How should address, delivery, and payment errors be recovered?",
        "How should consent remain distinct from purchase completion?",
        "How should a gift note or later charity choice enter without clutter?",
        "What should the order confirmation establish?",
        "How should made-to-order progress be represented?",
        "How should the customer return to progress after leaving?",
        "How should delays be shown before personal contact occurs?",
        "Where should delivery tracking live?",
        "Where should care instructions live before and after delivery?",
        "How should repair requests begin?",
        "How should returns gather useful evidence without burdening the customer?",
        "How should service remain human without creating a founder-personality interface?",
      ],
    ),
    chapter(
      "standards",
      "17",
      "Legal, privacy, access, and performance",
      "The non-negotiable operating floor across devices, abilities, languages, networks, and legal surfaces.",
      [
        "How should legal pages enter the identity rather than appear appended?",
        "What privacy information belongs near the address field?",
        "What analytics are permitted, and what is the proof that they remain cookieless?",
        "How should the site work without local storage or marketing scripts?",
        "What is the minimum keyboard path for every state?",
        "What screen-reader landmarks and names must remain stable?",
        "What contrast floor must every edition palette pass?",
        "What zoom and text-resizing behavior must be tested?",
        "What reduced-motion behavior must be tested?",
        "What language and direction changes must the layout tolerate?",
        "What is the image weight budget for first contact on mobile?",
        "What is the font weight and loading budget?",
        "What is the JavaScript budget?",
        "Which devices and browsers form the release matrix?",
        "What must render before any client script runs?",
        "How should slow, interrupted, or offline connections fail?",
        "What evidence is required before an edition-specific effect survives?",
      ],
    ),
    chapter(
      "extensions",
      "18",
      "Extensions and governance",
      "How the website system extends to email, social, certificates, packaging, service, and future revision.",
      [
        "Which website principles should govern editorial email?",
        "Which website elements should never be copied into email?",
        "How should social show finished work without becoming the primary place?",
        "Which digital record elements should appear on the physical certificate?",
        "Which page decisions may inform packaging for one edition?",
        "Which page decisions must never become permanent packaging rules?",
        "How should service messages remain recognizably Froni?",
        "How should the system record a confirmed decision?",
        "What evidence is required to reopen a confirmed decision?",
        "How should founder and cousin disagreement be represented internally?",
        "Which decisions require theological review?",
        "Which decisions require legal review?",
        "Which decisions require user testing?",
        "Which decisions require physical proof?",
        "What is the release checklist for each site state?",
        "What is the archive checklist when an edition closes?",
        "How should the system change when a later work proves an earlier rule wrong?",
        "What belongs in the final brand document, and what remains edition-specific?",
      ],
    ),
  ];

  window.FRONI_SITE_ROADMAP = {
    schemaVersion: 1,
    version: "2026-07-29.1",
    title: "Froni website decision roadmap",
    chapters,
  };
})();
