"use strict";

const REV12_CONFIG = {
  meta: {
    documentId: "FRN-001",
    revision: "12",
    buildDate: "23 Jul 2026",
    outputFilename: "Froni_FRN-001_Tech_Pack_Rev12.pdf",
    classification: "Custom-development technical pack",
    confidentiality: "Factory development and quotation",
  },

  contact: {
    name: "Ferdinand Toma",
    email: "house@froni.co",
  },

  order: {
    quantity: 200,
    sizes: ["S", "M", "L", "XL"],
    sizeSplit: "Final size split is supplied at order placement.",
    colorway: "Reactive-dyed black",
    factoryDateRequest: "Factory states its earliest committed ex-factory date after the approved pre-production sample.",
  },

  garment: {
    name: "Relaxed drop-shoulder pullover hoodie",
    patternBasis: "Fully custom cut and sew with factory pattern development",
    silhouette: "Relaxed fit with moderate drop shoulder and a straight, clean set-in sleeve seam",
    hood: "Three-panel, double-layer, self-fabric hood with two side panels and one center gusset",
    neck: "Blank neck with no applied label",
    exclusions: [
      "No pocket",
      "No drawcord",
      "No eyelets or aglets",
      "No body gussets",
      "No hardware",
      "No exterior print or applied graphic",
    ],
    flatNote: "Technical flats are schematic development drawings, not cutting patterns. Visual constants do not define garment measurements.",
  },

  approvalsBeforeBulkCutting: [
    "Factory pattern development",
    "Fit-sample approval",
    "Final graded pattern approval",
    "Production fabric approval",
    "Embroidery strike-off approval",
    "Pre-production sample approval",
  ],

  developmentStatus: "Bulk cutting may begin only after all six listed approvals are recorded.",

  revisionRecord: [
    "Hood and care-tape artwork authorities added; fibre, embroidery-thread, and factory-response content updated; icon frame ruling carried to Revision 13.",
    "Back icon acceptance artwork sheet, asymmetry pin map, and mirror judging references added.",
    "Hood assembly illustrations replaced with drawn illustrations; register corrections applied.",
    "Construction flats replaced with approved drawn flats; coded callouts repositioned.",
    "Set-in sleeve flats corrected; flat labels converted to coded callouts; interior verse locator image added; wording revised throughout.",
    "Quotation basis set to 200 garments with final size split supplied at order placement.",
    "Current blank-neck and four-decoration requirements applied.",
    "Construction-only vector flats and hood assembly schematics added.",
    "Construction, measurement, bill-of-materials, responsibility, development, and factory-response schedules added.",
    "Current artwork authorities and unavailable production deliverables identified.",
  ],

  pages: [
    { number: 1, type: "control", title: "Document control and development status" },
    { number: 2, type: "specification", title: "Garment, fabric, rib, and care specification" },
    { number: 3, type: "flatsFrontBack", title: "Construction flats: front and back" },
    { number: 4, type: "flatsViews", title: "Construction flats: side and hood views" },
    { number: 5, type: "hoodAssembly", title: "Three-panel hood and double-layer assembly" },
    { number: 6, type: "construction", title: "Construction matrix" },
    { number: 7, type: "pomBody", title: "Body and sleeve measurement methods" },
    { number: 8, type: "pomHood", title: "Hood and rib measurement methods" },
    { number: 9, type: "bom", title: "Bill of materials and sourcing evidence" },
    { number: 10, type: "artwork", title: "Front and back artwork authority and placement" },
    { number: 11, type: "hoodArtwork", title: "Hood artwork and embroidery acceptance" },
    { number: 12, type: "responsibility", title: "Development responsibility matrix" },
    { number: 13, type: "sequence", title: "Development sequence and approval outputs" },
    { number: 14, type: "response", title: "Factory acceptance and quotation response" },
  ],

  sectionTitles: [
    "Document control",
    "Development status",
    "Revision record",
    "Fixed garment specification",
    "Body fabric",
    "Rib and care",
    "Construction locations",
    "Measurement methods",
    "Artwork authority",
    "Embroidery process",
    "Acceptance checks",
    "Factory response",
  ],

  materials: {
    body: [
      ["Composition", "100% combed ring-spun cotton"],
      ["Knit", "Three-end loopback French terry, unbrushed interior"],
      ["Weight", "420-450 gsm, tolerance +/- 5%"],
      ["Body elastane", "Zero"],
      ["Dye", "Reactive-dyed black. Sulfur black is not accepted. Dye class confirmed in writing."],
      ["Finish", "Enzyme pre-shrunk, compacted, open-width finished, minimal softener"],
      ["Hand", "Dry, dense, firm, matte"],
      ["Residual shrinkage", "Maximum 5%"],
      ["Spirality", "Maximum 5%"],
      ["Pilling", "ISO 12945-2 grade 4+"],
      ["Wash fastness", "ISO 105-C06 grade 4-5+"],
      ["Rubbing fastness", "Dry 4+, wet 3-4+"],
      ["Light fastness", "Grade 4+"],
      ["Relaxation", "At least 24 hours after finishing and before cutting"],
      ["Shrinkage control", "Fully shrunk before cutting. No aggressive garment wash after assembly."],
    ],
    rib: [
      ["Structure", "2x2 rib"],
      ["Composition", "95-98% cotton, 2-5% elastane"],
      ["Color", "Matched reactive-dyed black"],
      ["Use", "Cuffs and hem"],
    ],
    evidence: [
      "Mill performance sheet with quotation",
      "Production-cloth swatch for approval",
      "Brushed version of the same cloth as a hand-feel control only",
    ],
    care: [
      "Machine wash 30 C inside out, gentle cycle",
      "Do not tumble dry",
      "Do not bleach",
      "Iron inside out only with pressing cloth",
      "Never iron directly on embroidery",
    ],
    tape: [
      "Printed care, fibre, origin, and wordmark tape only",
      "Oberstoff: 100% Baumwolle",
      "Body: 100% cotton",
      "Bündchen: 95-98% Baumwolle, 2-5% Elastan",
      "Rib: 95-98% cotton, 2-5% elastane",
      "Made in Portugal",
      "FRONI is permitted only on this printed tape",
    ],
  },

  decorations: [
    {
      id: "front_ornament",
      name: "Front ornamental embroidery",
      placement: "Front panel, uninterrupted ornament with the cross at its center",
      authority: "User-supplied front design reference photograph",
    },
    {
      id: "back_icon",
      name: "Back Christ Pantocrator embroidery",
      placement: "Centered on the back panel",
      authority: "Saint Catherine's scan",
    },
    {
      id: "hood_exterior",
      name: "Ο Ω Ν on the exterior hood gusset",
      placement: "Stacked upright from top to bottom on the exterior center gusset",
      authority: "Text locator only; production letterform pending",
    },
    {
      id: "hood_interior",
      name: "Verse inside the hood",
      placement: "Inner hood layer; exact position finalized from the approved fit sample",
      authority: "Text locator only; production lettering pending",
    },
  ],

  pom: {
    sizes: ["S", "M", "L", "XL"],
    existing: [
      { code: "A", name: "Body length", method: "High shoulder point to finished hem, straight", targets: [68, 70, 72, 74], tolerance: "+/- 1 cm" },
      { code: "B", name: "Chest 1 cm below armhole", method: "Half chest, edge to edge, 1 cm below armhole", targets: [57, 59, 61, 63], tolerance: "+/- 1 cm" },
      { code: "C", name: "Armhole", method: "Retained target; factory confirms the exact seam-line method", targets: [24, 25, 26, 27], tolerance: "+/- 1 cm" },
      { code: "D", name: "Cuff opening", method: "Half opening at finished cuff edge, relaxed", targets: [8, 8, 8.5, 9], tolerance: "+/- 1 cm" },
      { code: "E", name: "Sleeve length", method: "Shoulder seam to finished cuff along upper sleeve", targets: [57, 58, 59, 60], tolerance: "+/- 1 cm" },
      { code: "F", name: "Shoulder", method: "Neck seam to armhole seam along shoulder", targets: [18, 19, 20, 21], tolerance: "+/- 1 cm" },
      { code: "G", name: "Neck opening", method: "Straight across finished neckline", targets: [26, 26, 26, 26], tolerance: "+/- 1 cm" },
      { code: "H", name: "Bottom width", method: "Half width at body-to-rib seam", targets: [49, 51, 53, 55], tolerance: "+/- 1 cm" },
      { code: "I", name: "Bottom hem rib height", method: "Finished vertical rib height", targets: [6, 6, 6, 6], tolerance: "+/- 1 cm" },
      { code: "J", name: "Cuff rib length", method: "Finished cuff rib length along sleeve", targets: [6, 6, 6, 6], tolerance: "+/- 1 cm" },
      { code: "K", name: "Hood length", method: "Retained outer-shell target; factory confirms points", targets: [38, 38, 38, 38], tolerance: "+/- 1 cm" },
      { code: "L", name: "Hood width", method: "Retained outer-shell target; factory confirms points", targets: [26.5, 26.5, 26.5, 26.5], tolerance: "+/- 1 cm" },
      { code: "M", name: "Hood gusset width", method: "Finished center-gusset width at defined control line", targets: [10, 10, 10, 10], tolerance: "+/- 1 cm" },
    ],
    new: [
      { name: "Front neck drop", method: "High shoulder line to lowest front neckline point", targets: null, disposition: "Factory proposes at first pattern" },
      { name: "Back neck drop", method: "High shoulder line to center-back neckline", targets: null, disposition: "Factory proposes at first pattern" },
      { name: "Across shoulder", method: "Shoulder point to shoulder point across back", targets: null, disposition: "Factory proposes at first pattern" },
      { name: "Half bicep", method: "Half sleeve width at the factory-defined bicep line", targets: null, disposition: "Factory proposes at first pattern" },
      { name: "Sleeve width at defined points", method: "Half widths at factory-marked sleeve control lines", targets: null, disposition: "Derived from approved pattern" },
      { name: "Armhole measurement method", method: "Factory marks seam-line start, end, and path on pattern", targets: null, disposition: "Derived from approved pattern" },
      { name: "Hood face opening", method: "Finished opening measured along the seam line", targets: null, disposition: "Finalized from approved fit sample" },
      { name: "Hood depth", method: "Front opening to furthest back point on side panel", targets: null, disposition: "Finalized from approved fit sample" },
      { name: "Hood side-panel geometry", method: "Approved side-panel pattern perimeter and control points", targets: null, disposition: "Derived from approved pattern" },
      { name: "Center-gusset geometry", method: "Approved gusset length, width controls, and notches", targets: null, disposition: "Derived from approved pattern" },
      { name: "Hood neckline seam length", method: "Stitching-line length matched to the approved neckline", targets: null, disposition: "Derived from approved pattern" },
      { name: "Cuff rib width", method: "Cut and finished rib width stated separately", targets: null, disposition: "Factory proposes at first pattern" },
      { name: "Cuff relaxed opening", method: "Finished cuff opening measured relaxed", targets: null, disposition: "Finalized from approved fit sample" },
      { name: "Hem rib dimensions", method: "Cut length, cut height, and finished height", targets: null, disposition: "Derived from approved pattern" },
      { name: "Hem relaxed width", method: "Finished half width at lower rib edge, relaxed", targets: null, disposition: "Finalized from approved fit sample" },
    ],
    missingTolerance: "Factory proposes a production tolerance for approval where no tolerance is stated.",
  },

  constructionEngineeringBaseline: "For every seam and attachment area, the garment factory must propose stitch class, stitches per inch, seam allowance, seam finish, thread ticket, needle system, reinforcement, and stabilization as applicable, together with the row-specific requirements below.",

  construction: [
    {
      area: "Shoulder seam",
      fixed: "Clean exterior; preserve the relaxed drop-shoulder silhouette.",
      factoryProposal: "Propose stitch class, stitches per inch, seam allowance, seam finish, thread ticket, needle system, and reinforcement for the specified cloth.",
      firstFit: "Approve shoulder position, balance, comfort, and exterior appearance.",
      pps: "Confirm approved production construction and repeatability.",
    },
    {
      area: "Armhole seam",
      fixed: "Straight, clean set-in sleeve seam; no raglan construction.",
      factoryProposal: "Propose stitch class, stitches per inch, allowance, finish, needle system, thread, and clean bulk control.",
      firstFit: "Approve armhole shape, mobility, sleeve pitch, and exterior line.",
      pps: "Confirm seam shape and production method against the approved pattern.",
    },
    {
      area: "Sleeve underarm seam",
      fixed: "Continuous clean sleeve line without exterior decoration.",
      factoryProposal: "Propose stitch class, stitches per inch, allowance, finish, needle system, thread, and reinforcement at joins.",
      firstFit: "Approve sleeve rotation, comfort, and seam appearance.",
      pps: "Confirm production seam and junction alignment.",
    },
    {
      area: "Body side seam",
      fixed: "Standard side seams; no body gusset.",
      factoryProposal: "Propose stitch class, stitches per inch, allowance, finish, needle system, thread, and hem-junction control.",
      firstFit: "Approve balance, hang, and clean exterior.",
      pps: "Confirm production seam, alignment, and bulk control.",
    },
    {
      area: "Cuff rib attachment",
      fixed: "2x2 matched-black rib with the fixed fibre range.",
      factoryProposal: "Propose ratio, stitch class, stitches per inch, allowance, finish, needle system, thread, and join placement.",
      firstFit: "Approve opening, recovery, comfort, and sleeve transition.",
      pps: "Confirm approved dimensions and production recovery.",
    },
    {
      area: "Hem rib attachment",
      fixed: "2x2 matched-black rib; clean exterior with no waviness.",
      factoryProposal: "Propose ratio, stitch class, stitches per inch, allowance, finish, needle system, thread, and side-join treatment.",
      firstFit: "Approve relaxed width, recovery, body hang, and junctions.",
      pps: "Confirm approved dimensions and production method.",
    },
    {
      area: "Hood side-panel assembly",
      fixed: "Two outer side panels and two inner side panels in self fabric.",
      factoryProposal: "Propose stitch class, stitches per inch, allowance, finish, notches, needle system, thread, and bulk control.",
      firstFit: "Approve side-panel shape, face opening, volume, and drape.",
      pps: "Confirm approved pattern matching and clean exterior.",
    },
    {
      area: "Hood center-gusset assembly",
      fixed: "One center gusset per hood layer; exterior gusset carries the locator for Ο Ω Ν.",
      factoryProposal: "Propose stitch class, stitches per inch, allowance, finish, notches, needle system, thread, and alignment control.",
      firstFit: "Approve gusset geometry, centering, volume, and hood fall.",
      pps: "Confirm panel matching and centered placement.",
    },
    {
      area: "Inner and outer hood joining",
      fixed: "Double-layer self-fabric hood; embroidery backs hidden between layers.",
      factoryProposal: "Propose joining and turning sequence, stitch class, stitches per inch, allowance, finish, needle system, and bulk control.",
      firstFit: "Approve face-edge roll, weight, comfort, and clean finish.",
      pps: "Confirm no exposed embroidery back or unintended turn-out.",
    },
    {
      area: "Hood-to-neckline attachment",
      fixed: "Blank neck with no applied label; hood centered to the neckline.",
      factoryProposal: "Propose stitch class, stitches per inch, allowance, finish, needle system, thread, notches, and seam-bulk control.",
      firstFit: "Approve neckline shape, hood balance, comfort, and back-icon drape rule.",
      pps: "Confirm approved pattern match and clean attachment.",
    },
    {
      area: "Neckline stabilization",
      fixed: "No visible stabilizer and no applied neck branding.",
      factoryProposal: "State whether stabilization is needed and propose material, width, position, attachment, and wash behavior.",
      firstFit: "Approve comfort, recovery, and concealed appearance if used.",
      pps: "Confirm approved material and placement or record that none is used.",
    },
    {
      area: "Care-tape attachment",
      fixed: "Printed care, fibre, origin, and wordmark tape; no other label application.",
      factoryProposal: "Propose side-seam position, fold, attachment method, needle system, thread, and skin-contact finish.",
      firstFit: "Approve position, comfort, legibility, and content route.",
      pps: "Approve final printed tape and attachment.",
    },
    {
      area: "Embroidery stabilization and removal",
      fixed: "Front temporary tearaway or washaway only; localized permanent back cutaway only; no full-panel cutaway.",
      factoryProposal: "Propose named stabilizer types, layer count, hooping, removal, residue control, and panel handling.",
      firstFit: "Review drape, skin side, pucker, residue, and panel distortion after wash.",
      pps: "Confirm approved stabilizers, removal, and production handling.",
    },
  ],

  bom: [
    { item: "Body French terry", fixedSpec: "100% combed ring-spun cotton, three-end unbrushed loopback, reactive black, 420-450 gsm", sourcingParty: "Garment factory", approvalEvidence: "Mill sheet, swatch, composition and performance results", approvalStage: "Production-fabric approval" },
    { item: "Rib", fixedSpec: "2x2, 95-98% cotton and 2-5% elastane, matched reactive black", sourcingParty: "Garment factory", approvalEvidence: "Composition, recovery swatch, shade match", approvalStage: "Production-fabric approval" },
    { item: "Sewing thread", fixedSpec: "Factory proposes a thread suited to the specified cloth and clean exterior", sourcingParty: "Garment factory", approvalEvidence: "Construction proposal and sewn sample", approvalStage: "First fit and pre-production sample" },
    { item: "Embroidery thread", fixedSpec: "Madeira Frosted Matt 40 wt or approved Gunold equivalent; 60 wt permitted at the digitizer's discretion for finest face and hand detail", sourcingParty: "Garment factory under its embroidery contract", approvalEvidence: "Matte A/B test and production-cloth strike-offs", approvalStage: "Embroidery strike-off approval" },
    { item: "Embroidery bobbin", fixedSpec: "60-70 wt polyester", sourcingParty: "Garment factory under its embroidery contract", approvalEvidence: "Strike-off reverse and wash review", approvalStage: "Embroidery strike-off approval" },
    { item: "Embroidery needles", fixedSpec: "75/11 ballpoint", sourcingParty: "Garment factory under its embroidery contract", approvalEvidence: "Strike-off record and production setup", approvalStage: "Embroidery strike-off approval" },
    { item: "Temporary embroidery stabilizers", fixedSpec: "Front tearaway or washaway only; no permanent front cutaway", sourcingParty: "Garment factory under its embroidery contract", approvalEvidence: "Named proposal, removal sample, washed strike-off", approvalStage: "Embroidery strike-off approval" },
    { item: "Permanent localized back stabilizer", fixedSpec: "Localized upper-back cutaway tapered into the drape zone; no full-panel cutaway", sourcingParty: "Garment factory under its embroidery contract", approvalEvidence: "Named proposal, drape review, washed strike-off", approvalStage: "Embroidery strike-off approval" },
    { item: "Neckline stabilization", fixedSpec: "Factory proposes only if needed; must be concealed and compatible with wash requirements", sourcingParty: "Garment factory", approvalEvidence: "Material proposal and sewn sample, or written confirmation none is needed", approvalStage: "First fit and pre-production sample" },
    { item: "Printed care, fibre, origin, and wordmark tape", fixedSpec: "Required content only; blank neck and no other applied label", sourcingParty: "Garment factory", approvalEvidence: "Artwork proof, print sample, content check", approvalStage: "Pre-production sample approval" },
    { item: "Factory shipment polybag", fixedSpec: "Clean individual protective bag for factory shipment only", sourcingParty: "Garment factory", approvalEvidence: "Material and dimensions submitted", approvalStage: "Pre-production sample approval" },
    { item: "Factory shipment cartons", fixedSpec: "Export cartons suitable for factory shipment to Germany", sourcingParty: "Garment factory", approvalEvidence: "Carton specification and packing count", approvalStage: "Pre-production sample approval" },
  ],

  artwork: {
    front: {
      title: "Front ornamental embroidery",
      authority: "The supplied front design reference photograph controls the ornament. The cross is centered.",
      placement: "Centered on the approved front-panel pattern. Final embroidery geometry follows the production vector and the approved pattern.",
      stitch: [
        "Black-on-black ornamental linework revealed by texture in raking light",
        "Bean stitch, triple pass, 2.5 mm, flat",
        "Chain stitch is not accepted",
        "Planning range 35-60k stitches",
        "Four regenerated front files, one for each approved size pattern",
      ],
      hooping: [
        "One indexed frame advance and one horizontal routed join only",
        "The file contains a routed join corridor with no stitch crossing the split",
        "Registration jog maximum 1 mm",
        "Four-quadrant assembly is not accepted",
        "Resizing the design to fit a smaller field is not accepted",
      ],
      stabilizer: "Temporary tearaway or washaway only. No permanent front cutaway.",
    },
    back: {
      title: "Back Christ Pantocrator embroidery",
      authority: "The Saint Catherine's scan controls the face. Mirrored or regenerated images are not accepted as artwork authority.",
      placement: [
        "Centered on center back",
        "Halo apex target 12 cm below collar seam; accepted window 11-13 cm",
        "Icon height 46 cm on S and M",
        "Regenerated L and XL file approximately 48-50 cm high, subject to usable field",
        "Hood may cover the halo but must never cover the brow; verify on the physical fit sample",
      ],
      execution: [
        "Hand-directed needle painting with stitch angles following form",
        "Automated photo-stitch with uniform parallel scan lines is rejected",
        "40 wt thread throughout; 60 wt permitted at the digitizer's discretion for finest face and hand detail",
        "One field position with no joined embroidery on the back panel",
        "Usable field must allow artwork plus 2 cm hooping margin on each side",
        "If usable field width is 45 cm, icon width caps at 43 cm and height follows the artwork aspect",
        "Two regenerated back files: S/M and L/XL, with densities retuned rather than scaled",
      ],
      stabilizer: "Localized upper-back cutaway tapered into the drape zone. No full-panel cutaway.",
    },
    hoodExterior: {
      string: "Ο Ω Ν",
      placement: "Exterior center gusset, three glyphs stacked upright from top to bottom and centered",
      color: "Marigold, target C9A227; factory submits nearest thread shades for the strike-off A/B",
      reference: "The supplied hood photograph controls the intended embroidered appearance and confirms the upright vertical stack.",
      note: "Production letterform artwork: Froni_Edition_One_Hood_Exterior_Lettering_Rev01.svg. EB Garamond regular capitals. Cap height 30 mm, baseline pitch 45 mm, glyph block centered on the gusset.",
    },
    hoodInterior: {
      unit: "Fear not, for I am with you - Isaiah 41:10",
      placement: "Inner shell layer with stitch back hidden between hood layers. Exact position finalized from the approved fit sample.",
      lettering: [
        "Italic lettering from approved production artwork",
        "X-height 7 mm minimum on every garment size",
        "Escalate to 8-9 mm if italic counters close on production cloth",
        "Repeat the full unit 2-3 times as clean fit permits",
        "Planning range 5-8k stitches",
        "One file with fixed lettering size and variable repeat",
      ],
      reference: "The photograph shows intended interior verse placement and proportion only.",
      note: "Production lettering artwork: Froni_Edition_One_Hood_Interior_Verse_Rev01.svg. EB Garamond italic. X-height fixed at 7 mm; single-line unit, 26.9 cm advance; the unit tiles end to end with a 20 mm trailing space; repeat 2 to 3 units as clean fit permits. The verse runs as a single-line band; exact position finalized from the approved fit sample.",
    },
  },

  embroidery: {
    sequence: "All four decorations are embroidered on flat panels before garment assembly.",
    setup: [
      ["Main embroidery thread", "Madeira Frosted Matt 40 wt or approved Gunold equivalent"],
      ["Face and hand detail", "40 wt; 60 wt at the digitizer's discretion"],
      ["Bobbin", "60-70 wt polyester"],
      ["Needles", "75/11 ballpoint"],
      ["Colors", "Maximum 15 in one setup with no mid-run rethreading"],
      ["Gold", "Marigold, target C9A227; factory submits nearest thread shades for the strike-off A/B"],
    ],
    backBudget: [
      ["Face and hands, layered needle painting", "40-50k"],
      ["Hair and beard, directional satin", "12-16k"],
      ["Robe, medium fill", "50-65k"],
      ["Halo and Gospel book, radiating satin", "26-34k"],
      ["Edge feathering and details", "6-10k"],
      ["Back total planning range", "Approximately 145-185k"],
      ["Hard cap", "180k S/M, 200k L/XL"],
    ],
    budgetNote: "The digitizer reconciles zone planning ranges to the hard cap in the submitted stitch plan.",
    filePackage: [
      "Four regenerated front files, one per approved size pattern",
      "Two regenerated back files, S/M and L/XL, with retuned densities",
      "One hood exterior lettering file",
      "One hood interior verse file",
      "Editable native Wilcom .EMB masters and all graded production outputs",
    ],
    ownership: [
      "Editable native Wilcom .EMB masters and graded production outputs are delivered to and owned by Froni.",
      "Digitizer supplies files and revisions, including one remote tuning round after the first production-cloth strike-off.",
      "Physical strike-offs remain under the garment factory's contract and responsibility, including subcontracted embroidery.",
      "The garment factory bears the cost of strike-offs repeated due to embroidery execution faults.",
      "Digitizing fee includes revisions until an approved production sew-out on final fabric.",
    ],
    acceptance: [
      "Production-cloth face strike-off photographed straight on, split vertically, and mirrored into two composites. Reject if the two composites read as the same face.",
      "Matte thread A/B comparison on the same production-cloth swatch under raking light.",
      "Full-size front strike-off under raking light; inspect routed join corridor and maximum 1 mm registration jog.",
      "Hood-lettering strike-off on production cloth; verify Greek locator placement and italic apertures at the specified minimum x-height.",
      "Wash trial: one swatch for 25-30 cycles at 40-60 C plus tumble, reviewed for pucker, fade, and thread integrity.",
      "One full sample for five industrial washes before production approval.",
      "Back icon must use one field with no join; hood drape may cover halo but never brow.",
    ],
  },

  responsibilities: [
    { scope: "Fixed garment and material requirements", owner: "Froni", deliverable: "This pack and written clarifications", approval: "Froni confirms any revision" },
    { scope: "Factory pattern development", owner: "Garment factory", deliverable: "First pattern, corrected pattern, graded pattern, measurement chart", approval: "Froni approves fit sample and final graded pattern" },
    { scope: "Factory construction proposal", owner: "Garment factory", deliverable: "Area-by-area construction engineering without changing fixed requirements", approval: "Froni approves proposal, first fit, and pre-production sample" },
    { scope: "Fabric and trim sourcing", owner: "Garment factory", deliverable: "Mill data, swatches, test evidence, trim proposals", approval: "Froni approves production fabric and trims" },
    { scope: "Digitizing files and revisions", owner: "External digitizer", deliverable: "Native masters, graded files, stitch plan, color map, tuning revisions", approval: "Froni approves files through physical sew-outs" },
    { scope: "Embroidery subcontracting", owner: "Garment factory", deliverable: "Subcontractor control, setup, physical strike-offs, production embroidery", approval: "Garment factory remains the sole contracting and responsible party to Froni" },
    { scope: "Fit-dependent items", owner: "Garment factory with Froni approval", deliverable: "Final balance, hood geometry, measurement points, placement adjustments", approval: "Finalized from the approved fit sample" },
    { scope: "Strike-off-dependent items", owner: "Garment factory with digitizer support", deliverable: "Thread, density, stabilizer, join, lettering, wash results", approval: "Froni approves production-cloth strike-offs" },
    { scope: "Pre-production-sample-dependent items", owner: "Garment factory", deliverable: "Production construction, graded measurement chart, final tape, packing method", approval: "Froni approves the pre-production sample" },
    { scope: "Bulk manufacture and final inspection", owner: "Garment factory", deliverable: "Garments matching the approved pre-production sample and evidence", approval: "Release after final inspection and shipment documents" },
  ],

  developmentStages: [
    { stage: "Factory technical review and feasibility confirmation", approvalOutput: "Signed yes or no acceptance, deviations list, field data, development and quotation inputs" },
    { stage: "Construction proposal", approvalOutput: "Complete area-by-area engineering proposal approved in writing" },
    { stage: "First pattern", approvalOutput: "First custom pattern, pattern card, proposed point-of-measurement values, and measurement method sheet" },
    { stage: "First fit sample without final embroidery where appropriate", approvalOutput: "Physical fit sample with completed measurement report and marked corrections" },
    { stage: "Fit corrections", approvalOutput: "Corrected physical fit sample, revised pattern, completed measurement report, and review record against fit comments" },
    { stage: "Approved graded pattern and updated measurement chart", approvalOutput: "Approved graded nest, pattern files, and final measurement chart" },
    { stage: "Production-fabric approval", approvalOutput: "Approved swatch, mill data, performance evidence, shade and hand confirmation" },
    { stage: "Embroidery strike-offs on production fabric", approvalOutput: "Approved front, back, hood, mirror, matte, stabilizer, and wash evidence" },
    { stage: "Embroidered pre-production sample", approvalOutput: "Complete embroidered garment reviewed for placement, drape, fit, and construction" },
    { stage: "Pre-production sample approval", approvalOutput: "Signed pre-production-sample approval with sealed sample, chart, tape, bill of materials, and production method" },
    { stage: "Bulk production", approvalOutput: "In-line records against the sealed pre-production sample and approved production controls" },
    { stage: "Final inspection and shipment", approvalOutput: "Final inspection report, packing list, shipment evidence, and accepted release" },
  ],

  factoryResponse: [
    "Yes or no on accepting the fully custom cut-and-sew development",
    "Pattern-development price",
    "First fit-sample price",
    "Corrected fit-sample price",
    "Pre-production sample price",
    "Embroidery setup and strike-off charges",
    "Provisional bulk unit price at 200 units",
    "Fabric minimum and fabric lead time",
    "Sample lead time",
    "Bulk lead time after the approved pre-production sample",
    "Earliest committed ex-factory date after the approved pre-production sample",
    "Maximum usable embroidery field in centimetres",
    "Embroidery machine make and field configuration",
    "Confirmation that embroidery remains under the garment factory's contract and responsibility",
    "Payment terms",
    "Incoterm",
    "Shipping estimate to Germany",
    "Factory closure periods in the next six months",
  ],
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = REV12_CONFIG;
}

if (typeof window !== "undefined") {
  window.REV12_CONFIG = REV12_CONFIG;
}
